name: Test installations

on:
  pull_request:
    branches: [master, dev]
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, pypy2, pypy3]
    steps: 
        - name: Test solc-select installation
        run:  | 
           pip3 install solc-select
           solc-select install all 
           solc-select use 0.8.0