name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  tests:
    runs-on: windows-latest
    strategy:
      matrix:
        type: "windows"
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install solc-select
      run: |
        python3 setup.py install
        solc-select install all
    - name: Run Tests
      env:
        TEST_TYPE: ${{ matrix.type }}
      run: |
        bash scripts/travis_test_${TEST_TYPE}.sh