---
name: Install Windows solc-select

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  pull_request:
    branches: [master, dev]
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  build:
    name: Install test
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install all solc versions
        run: |
          pip3 install solc-select
          solc-select install all
      - name: Test minimum release
        run: |
          solc-select use 0.4.1
      - name: Test 0.8.0
        run: |
          solc-select use 0.8.0